#! /bin/sh

#Configuracion de fuanito

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X # bspc monitor HDMI-A-0 -d X

window_gap=15
border=2
polybar_height=27
top_padding=$polybar_height # $(($polybar_height-$window_gap-10))

bspc config border_width            $border
bspc config normal_border_color     "#000000"
bspc config focused_border_color    "#FFFFFF"

bspc config window_gap              $window_gap
bspc config top_padding             $top_padding

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules

bspc rule -r "*"
bspc rule -a "*" state=tiled

xsetroot -cursor_name left_ptr &
compton -f -D 3 &

nitrogen --restore &
polybar mybar &
